### ISSUE TITLE
LobbyDataUpdate Signal

### ISSUE THREAD

**Issue by VestedGrammar** [LauraWebdev/GodotSteam_CSharpBindings#32]
When trying to connect the LobbyDataUpdate signal to a function, there appears to be an issue.

Analogous signals in Steam.Matchmaking.Signals are associated with a corresponding delegate which can be used as a type to store the delegate and allow the signal to be disconnected when the Node exits the tree.

For example:

```
   Steam.LobbyCreatedEventHandler _lobbyCreated;
  
  _lobbyCreated = (connect, lobbyId) => {
			  OnLobbyCreated(connect, lobbyId);
		  };

		Steam.LobbyCreated += _lobbyCreated;

```

There is no equivalent delegate for LobbyDataUpdate, which is instead initialized as an Action type. Trying to use an Action returns the error ThrowIfArgCoutnMismatch because LobbyDataUpdate is trying to pass 3 arguments.

Now it's incredibly likely I'm simply approaching this wrong, but is there a reason that a delegate type was created for every signal in Steam.Matchmaking.Signals, but NOT for LobbyDataUpdate?

**Comment by VestedGrammar** [comment]
I made these changes to my local version of the addon[here](https://github.com/LauraWebdev/GodotSteam_CSharpBindings/compare/main...VestedGrammar:GodotSteam_CSharpBindings:patch-1) and it fixed the issue.

**Comment by SlejmUr** [comment]
Create a PR and have a high chance to get applied :)
