### ISSUE TITLE
Type/Class cleanup: Steam.Input.cs

### ISSUE THREAD

**Issue by LauraWebdev** [LauraWebdev/GodotSteam_CSharpBindings#8]

**Comment by Formedras** [comment]
Multiple functions in Steam.Input request handles in the form of signed long values. In all cases, the correct type to send is an unsigned long.

In addition, the "flags" arguments, such as in `GetGlyphSVGForActionOrigin`, should be corresponding enums with the `[Flags]` property. (For `GetGlyphSVGForActionOrigin` and `GetGlyphPNGForActionOrigin`, for example, the GDScript enum is Steam.InputGlyphStyle. Note that GDScript enums don't work properly as bitflags, so combining them in GDScript will cause warnings to appear. For these bindings, it's probably best to request arguments as flags, and then cast back to ulong for the call to GDScript.)
